### ISSUE TITLE
German

### ISSUE THREAD

**Issue by tomerhart** [pacokwon/lds-scripture-translations#1]
Hi! Thank you for all the work you've put into this, it's truly remarkable, I love it!
When you find the time, could you please add German (deu) to the available translations?

**Comment by pacokwon** [comment]
I've just added German. The process is [automated](https://github.com/pacokwon/scripture-tools/tree/main/verse-collector) though, and I don't know any German to verify the correctness.

Please let me know if there's anything wrong. Thanks!

**Comment by tomerhart** [comment]
Fantastic, thank you so much!
